[build-system]
requires = ["setuptools ~= 58.0", "cython ~= 0.29.0"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "Login Test"
depedencies = ["SQLAlchemy==2.0"]
version = "2.0"